PNT1/Models/Venta.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PNT1.Models
{
    public class Venta
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [BindNever]
        public int VentaId { get; set; }

        [Display(Name = "Nombre")]
        [StringLength(20)]
        [Required(ErrorMessage ="Ingrese su nombre")]
        public string Nombre { get; set; }

        [Display(Name = "Apellido")]
        [StringLength(20)]
        [Required(ErrorMessage = "Ingrese su apellido")]
        public string Apellido { get; set; }

        [Display(Name = "Direccion")]
        [StringLength(40)]
        [Required(ErrorMessage = "Ingrese su direccion")]
        public string Direccion { get; set; }

        [Display(Name = "Ciudad")]
        [StringLength(20)]
        [Required(ErrorMessage = "Ingrese su ciudad")]
        public string Ciudad { get; set; }

        [Display(Name = "Codigo Postal")]
        [StringLength(4, MinimumLength =4)]
        [Required(ErrorMessage = "Ingrese el codigo postal")]
        public string CodigoPostal { get; set; }


        [Display(Name = "Telefono")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Ingrese el telefono")]
        public string Telefono { get; set; }

        public List<VentaDetalle> VentaDetalle { get; set; }

        [BindNever]
        public double VentaTotal { get; set; }

        [BindNever]
        public DateTime Fecha { get; set; }

    }
}

PNT1/Controllers/VentaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PNT1.Models;

namespace PNT1.Controllers
{
    [Authorize]
    public class VentaController : Controller
    {
        
        private readonly IVentaRepositorio _ventaRepositorio;
        private readonly Carrito _carrito;

        public VentaController(IVentaRepositorio ventaRepositorio, Carrito carrito)
        {
            _ventaRepositorio = ventaRepositorio;
            _carrito = carrito;

        }

        // Get
        public IActionResult Checkout()
        {
            return View();
        }

        // Post
        [HttpPost]
        public IActionResult Checkout(Venta venta)
        {
            _carrito.carritoItems = _carrito.GetCarritoItems();

            if(_carrito.carritoItems.Count == 0)
            {
                ModelState.AddModelError("","El carrito esta vacio");   
            }

            if (ModelState.IsValid)
            {
                _ventaRepositorio.CrearVenta(venta);
                _carrito.LimpiarCarrito();

                return RedirectToAction("CheckoutCompleto");
            }

            return View(venta);
        }

        public IActionResult CheckoutCompleto()
        {
            ViewBag.MensajeCheckout = "Gracias por tu compra!";

            return View();
        }
    }
}

PNT1/Views/Venta/Checkout.cshtml
@model Venta

<form asp-action="Checkout" method="Post" class="form-horizontal" role="form">
    <h1 id="titulo">Completa la siguiente info!</h1>

    <div class="form-group">
        <label class="text-login" asp-for="Nombre" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label class="text-login" asp-for="Apellido" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Apellido" class="form-control" />
            <span asp-validation-for="Apellido" class="danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label class="text-login" asp-for="Direccion" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Direccion" class="form-control" />
            <span asp-validation-for="Direccion" class="danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="text-login" asp-for="Ciudad" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Ciudad" class="form-control" />
            <span asp-validation-for="Ciudad" class="danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="text-login" asp-for="CodigoPostal" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="CodigoPostal" class="form-control" />
            <span asp-validation-for="CodigoPostal" class="danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="text-login" asp-for="Telefono" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Telefono" class="form-control" />
            <span asp-validation-for="Telefono" class="danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-dark" id="button-carrito" value="Comprar" asp-controller="Venta" asp-action="Checkout" />
        </div>
    </div>

</form>

PNT1/Views/Venta/CheckoutCompleto.cshtml
<h1 id="titulo">@ViewBag.MensajeCheckout</h1>

PNT1/Views/Venta/Index.cshtml
<form>

</form>