PNT1/Controllers/CarritoController.cs
using Microsoft.AspNetCore.Mvc;
using PNT1.Models;
using PNT1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PNT1.Controllers
{
    public class CarritoController : Controller

    {
        private readonly IItemRepositorio _itemRepositorio;
        private readonly Carrito _carrito;


        public CarritoController(IItemRepositorio itemRepositorio, Carrito carrito)
        {
            _itemRepositorio = itemRepositorio;
            _carrito = carrito;

        }
        public ViewResult Index()
        {
            _carrito.carritoItems = _carrito.GetCarritoItems();

            var carritoViewModel = new CarritoViewModel
            {
                Carrito = _carrito,
                CarritoTotal = _carrito.GetTotalCarrito()
            };

            return View(carritoViewModel);
        }

        public RedirectToActionResult AgregarAlCarrito(int itemId)
        {
            var itemSeleccionado = _itemRepositorio.GetAllItems.FirstOrDefault(c => c.Id == itemId);

            if(itemSeleccionado != null)
            {
                _carrito.AgregarAlCarrito(itemSeleccionado, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult BorrarDelCarrito(int itemId)
        {
            var itemSeleccionado = _itemRepositorio.GetAllItems.FirstOrDefault(c => c.Id == itemId);

            if (itemSeleccionado != null)
            {
                _carrito.BorrarDelCarrito(itemSeleccionado);
            }

            return RedirectToAction("Index");
        }


    }
}

PNT1/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PNT1.Models;
using PNT1.ViewModels;

namespace PNT1.Controllers
{
    public class ItemsController : Controller
    {
        private readonly IItemRepositorio _itemRepositorio;

        public ItemsController(IItemRepositorio itemRepositorio)
        {
            _itemRepositorio = itemRepositorio;
        }

        // GET: Items/List
        public IActionResult List()
        {
            var itemListViewModel = new ItemListViewModel();
            itemListViewModel.Items = _itemRepositorio.GetAllItems; 

            return View(itemListViewModel);
        }

        public IActionResult Details(int id)
        {
            var item = _itemRepositorio.GetItemById(id);
            if(item == null)
            {
                return NotFound();
            } else
            {
                return View(item);
            }
        }
    }
}

PNT1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Kingstein Beatz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik+Spray+Paint&family=Secular+One&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 navbar-toggle">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Items" asp-action="List" id="titulo">Kingstein Beatz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Carrito" asp-action="Index">Carrito</a>
                        </li>
                        @await Component.InvokeAsync("CarritoSummary")
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        @RenderSection("Scripts", required: false)
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PNT1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>